config/routes.rb
Twodbs::Application.routes.draw do

  root 'examiners#index'

  
  resources :examiners

end

app/models/examiner.rb
class Examiner < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/examiners_controller.rb
class ExaminersController < ApplicationController
  before_action :set_examiner, only: [:show, :edit, :update, :destroy]

  # GET /examiners
  # GET /examiners.json
  def index
    @examiners = Examiner.all
  end

  # GET /examiners/1
  # GET /examiners/1.json
  def show
  end

  # GET /examiners/new
  def new
    @examiner = Examiner.new
  end

  # GET /examiners/1/edit
  def edit
  end

  # POST /examiners
  # POST /examiners.json
  def create
    @examiner = Examiner.new(examiner_params)

    respond_to do |format|
      if @examiner.save
        format.html { redirect_to @examiner, notice: 'Examiner was successfully created.' }
        format.json { render action: 'show', status: :created, location: @examiner }
      else
        format.html { render action: 'new' }
        format.json { render json: @examiner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examiners/1
  # PATCH/PUT /examiners/1.json
  def update
    respond_to do |format|
      if @examiner.update(examiner_params)
        format.html { redirect_to @examiner, notice: 'Examiner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @examiner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examiners/1
  # DELETE /examiners/1.json
  def destroy
    @examiner.destroy
    respond_to do |format|
      format.html { redirect_to examiners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_examiner
      @examiner = Examiner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def examiner_params
      params.require(:examiner).permit(:firstname, :lastname, :current)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examiners_helper.rb
module ExaminersHelper
end

app/views/examiners/_form.html.erb
<%= form_for(@examiner) do |f| %>
  <% if @examiner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@examiner.errors.count, "error") %> prohibited this examiner from being saved:</h2>

      <ul>
      <% @examiner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.check_box :current %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/examiners/edit.html.erb
<h1>Editing examiner</h1>

<%= render 'form' %>

<%= link_to 'Show', @examiner %> |
<%= link_to 'Back', examiners_path %>

app/views/examiners/index.html.erb
<h1>Listing examiners</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Current</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @examiners.each do |examiner| %>
      <tr>
        <td><%= examiner.firstname %></td>
        <td><%= examiner.lastname %></td>
        <td><%= examiner.current %></td>
        <td><%= link_to 'Show', examiner %></td>
        <td><%= link_to 'Edit', edit_examiner_path(examiner) %></td>
        <td><%= link_to 'Destroy', examiner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Examiner', new_examiner_path %>

app/views/examiners/new.html.erb
<h1>New examiner</h1>

<%= render 'form' %>

<%= link_to 'Back', examiners_path %>

app/views/examiners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @examiner.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @examiner.lastname %>
</p>

<p>
  <strong>Current:</strong>
  <%= @examiner.current %>
</p>

<%= link_to 'Edit', edit_examiner_path(@examiner) %> |
<%= link_to 'Back', examiners_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twodbs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>